const APP={lang:localStorage.irnrLang||'ru',dark:localStorage.irnrDark==='1',citizen:null};
const citizens={
 '169528':{series:'0228',num:'169528',fio:'Казаков Мирослав Михайлович',role:'Верховный Господин',dob:'—',img:'irnr_flag.png',anime:true},
 '856370':{series:'7355',num:'856370',fio:'Афоничев Богдан Евгениевич',role:'Гражданин ИРНР',dob:'06.09.2012',img:'bogdan.png'}
};
const news=[
 ['30.09.2026','Первое заявление на гражданство','В государственный портал поступило первое заявление на получение гражданства ИРНР.','citizenship'],
 ['30.09.2026','Обновление портала','Запущены разделы подачи заявок на образование и здравоохранение, обновлена структура портала.','update'],
 ['01.10.2026','Первый бумажный паспорт','Изготовлен первый физический бумажный паспорт ИРНР.','passport'],
 ['01.10.2026','Новое обновление сайта','Добавлены тёмная тема, личный кабинет гражданина, документы, статусы программ и новые разделы.','update'],
 ['01.10.2026','Новая валюта в разработке','Начата разработка нового дизайна государственной валюты ИРНР.','currency']
];
function tr(ru,en){return APP.lang==='ru'?ru:en}
function layout(content){document.body.classList.toggle('dark',APP.dark);document.documentElement.lang=APP.lang;document.getElementById('app').innerHTML=`<div class="top"></div><header class="nav"><div class="navin"><a class="brand" href="#/"><img class="flag" src="irnr_flag.png"><span>ИРНР<small>${tr('Государственный портал','State portal')}</small></span></a><nav class="navlinks"><button onclick="go('/')">${tr('Главная','Home')}</button><button onclick="go('/citizens')">${tr('Граждане','Citizens')}</button><button onclick="go('/constitution')">${tr('Конституция','Constitution')}</button><button onclick="go('/news')">${tr('Новости','News')}</button><button onclick="go('/cabinet')">${tr('Личный кабинет','Cabinet')}</button></nav><button class="iconbtn" onclick="toggleDark()">${APP.dark?'☀️':'🌙'}</button><button class="iconbtn" onclick="toggleLang()">${APP.lang==='ru'?'EN':'RU'}</button></div></header><main>${content}</main><footer class="footer">${tr('Израильская Ростовская Народная Республика · Государственный портал','Israel Rostov People’s Republic · State portal')}<br><span>${tr('Проект является вымышленным ролевым/юмористическим проектом.','This is a fictional roleplay/humour project.')}</span></footer><div id="modal" class="modal"><div class="modalbox" id="modalbox"></div></div><div id="toast" class="toast"></div>`}
function go(path){location.hash=path}
function toggleDark(){APP.dark=!APP.dark;localStorage.irnrDark=APP.dark?'1':'0';render()}
function toggleLang(){APP.lang=APP.lang==='ru'?'en':'ru';localStorage.irnrLang=APP.lang;render()}
function modal(html){document.getElementById('modalbox').innerHTML=html;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
window.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function home(){return `<section class="hero"><div><div class="eyebrow">${tr('Официальный портал','Official portal')}</div><h1>${tr('Израильская Ростовская Народная Республика','Israel Rostov People’s Republic')}</h1><p>${tr('Единая точка доступа к государственным сервисам, документам, новостям и информации Республики.','A single access point to state services, documents, news and information.')}</p><div class="actions"><button class="btn primary" onclick="go('/cabinet')">${tr('Личный кабинет','Personal cabinet')}</button><button class="btn" onclick="go('/constitution')">${tr('Конституция','Constitution')}</button></div></div><div class="hero-side"><img src="irnr_flag.png" alt="Флаг ИРНР"></div></section><div class="grid"><div class="card tile" onclick="go('/education')"><span class="badge">27</span><h3>${tr('Образование','Education')}</h3><p class="muted">${tr('Подача заявки на организацию или финансирование обучения.','Apply for education organization or funding.')}</p></div><div class="card tile" onclick="go('/health')"><span class="badge">28</span><h3>${tr('Здравоохранение','Healthcare')}</h3><p class="muted">${tr('Доступная государственная медицинская помощь и регистрация программы.','Accessible public healthcare and program registration.')}</p></div><div class="card tile" onclick="go('/currency')"><span class="badge">RHD</span><h3>${tr('Государственная валюта','State currency')}</h3><p class="muted">${tr('Курс дубля и новости о новом дизайне валюты.','Duble exchange information and currency design news.')}</p></div></div><section class="card" style="margin-top:22px"><h2>${tr('Последние новости','Latest news')}</h2><div class="news">${news.slice(0,4).map(n=>`<div class="newsitem"><div class="muted">${n[0]}</div><a href="#/news/${n[3]}">${n[1]}</a><div>${n[2]}</div></div>`).join('')}</div></section>`}
function citizensPage(){return `<div class="page-title"><div class="eyebrow">${tr('Реестр','Registry')}</div><h1>${tr('Граждане ИРНР','Citizens of IRNR')}</h1><p class="muted">${tr('Нажмите на профиль для просмотра открытых сведений.','Open a profile to view public information.')}</p></div><div class="grid">${Object.values(citizens).map(c=>`<div class="card tile" onclick="profile('${c.num}')"><div class="cabinet-head"><img class="avatar" src="${c.img}"><div><h3>${c.fio}</h3><div class="muted">${c.role}</div></div></div></div>`).join('')}</div>`}
function profile(num){const c=citizens[num];let html=`<div class="cabinet-head"><img class="avatar" src="${c.img}"><div><h2 ondblclick="kOn()" style="cursor:pointer">${c.fio}</h2><div class="muted">${c.role}</div></div></div><hr><p><b>${tr('Дата рождения','Date of birth')}:</b> ${c.dob}</p><p>${tr('Открытая информация профиля. Документные реквизиты доступны владельцу через личный кабинет.','Public profile information. Document details are available to the owner in the personal cabinet.')}</p><button class="btn" onclick="closeModal()">OK</button>`;modal(html)}
function kOn(){const c=citizens['169528'];modal(`<div class="k-on" style="padding:18px;border-radius:12px"><span class="badge">K-ON!</span><h2>${c.fio}</h2><p>${tr('Альтернативное оформление профиля: гитара, аниме и любовь к K-On!','Alternative profile theme: guitar, anime and love for K-On!')}</p><p class="muted">${tr('Это декоративная пасхалка проекта.','This is a decorative project easter egg.')}</p></div>`)}
function constitution(){return `<div class="page-title"><div class="eyebrow">${tr('Основной закон','Basic law')}</div><h1>${tr('Конституция ИРНР','Constitution of IRNR')}</h1><p class="muted">${tr('Полный текст сохранён в проекте. Статья 27 открывает сервис образования.','The full text is included in the project. Article 27 opens the education service.')}</p></div><div class="card constitution" id="constitutionText">Загрузка…</div>`}
async function loadConstitution(){try{const t=await fetch('constitution.txt').then(r=>r.text());const el=document.getElementById('constitutionText');el.innerHTML=t.replace(/(Статья 27\. Образование[\s\S]*?)(?=\nСтатья 28\.)/,'<span class="article main" onclick="go(\'/education\')">$1</span>')}catch(e){}}
function cabinet(){return `<div class="page-title"><div class="eyebrow">${tr('Госуслуги','State services')}</div><h1>${tr('Личный кабинет гражданина','Citizen personal cabinet')}</h1></div><div class="card"><form class="form" onsubmit="login(event)"><div class="two"><div><label>${tr('Серия','Series')}<input id="series" inputmode="numeric" required></label></div><div><label>${tr('Номер','Number')}<input id="num" inputmode="numeric" required></label></div></div><button class="btn primary">${tr('Войти','Sign in')}</button></form><p class="muted">${tr('Для демонстрационного проекта используются реквизиты из реестра граждан.','This demo project uses the registry credentials.')}</p></div>`}
function login(e){e.preventDefault();const s=document.getElementById('series').value.trim(),n=document.getElementById('num').value.trim(),c=Object.values(citizens).find(x=>x.series===s&&x.num===n);if(!c){toast(tr('Гражданин не найден','Citizen not found'));return}APP.citizen=c;renderCabinet(c)}
function renderCabinet(c){layout(`<div class="page-title"><div class="eyebrow">${tr('Личный кабинет','Personal cabinet')}</div><h1>${c.fio}</h1></div><div class="card"><div class="cabinet-head"><img class="avatar" src="${c.img}"><div><h2>${c.role}</h2><div class="status"><span class="dot"></span>${tr('Личный кабинет активен','Cabinet active')}</div></div></div><div style="margin-top:22px" class="doc"><details><summary>${tr('Документы','Documents')}</summary><div class="docbody"><p><b>${tr('Серия','Series')}:</b> ${c.series}</p><p><b>${tr('Номер','Number')}:</b> ${c.num}</p><p><b>${tr('Выдан','Issued by')}:</b> Государственными органами ИРНР</p></div></details></div></div><div class="grid"><div class="card tile" onclick="go('/education')"><div class="plus">＋</div><h3>${tr('Образование','Education')}</h3><p class="muted">${tr('Заявка не зарегистрирована','Application not registered')}</p></div><div class="card tile" onclick="go('/health')"><div class="plus">＋</div><h3>${tr('Здравоохранение','Healthcare')}</h3><p class="muted">${tr('Заявка не зарегистрирована','Application not registered')}</p></div><div class="card"><span class="badge">IRNR</span><h3>${tr('Статус гражданина','Citizen status')}</h3><p>${c.role}</p></div></div><div class="actions" style="margin-top:18px"><button class="btn" onclick="APP.citizen=null;go('/cabinet')">${tr('Выйти','Sign out')}</button></div>`)}
function service(type){const edu=type==='education';return `<div class="page-title"><div class="eyebrow">${edu?'Статья 27':'Статья 28'}</div><h1>${edu?tr('Образование','Education'):tr('Здравоохранение','Healthcare')}</h1><p class="muted">${edu?tr('Заявка на организацию или финансирование обучения после пятого класса.','Application for education organization or funding after fifth grade.'):tr('Заявка на регистрацию в программе доступной государственной медицинской помощи.','Application for accessible public healthcare program.')}</p></div><div class="card"><form class="form" onsubmit="submitService(event,'${type}')"><div class="two"><label>${tr('Фамилия','Surname')}<input id="ln" required></label><label>${tr('Имя','Name')}<input id="fn" required></label></div><label>${tr('Отчество','Patronymic')}<input id="mn"></label><div class="two"><label>${tr('Серия гражданства','Citizenship series')}<input id="cs" inputmode="numeric" required></label><label>${tr('Номер гражданства','Citizenship number')}<input id="cn" inputmode="numeric" required></label></div><label>${edu?tr('Цель обучения','Education purpose'):tr('Цель обращения','Purpose')}<textarea id="purpose" required></textarea></label><button class="btn primary">${tr('Отправить заявку','Submit application')}</button></form></div>`}
function submitService(e,type){e.preventDefault();toast(tr('Заявка отправлена в демонстрационную систему','Application sent to the demo system'));e.target.reset()}
function currency(){return `<div class="page-title"><div class="eyebrow">RHD</div><h1>${tr('Государственная валюта','State currency')}</h1></div><div class="grid"><div class="card"><span class="badge">USD</span><h2>1 USD = 850 дублей</h2><p class="muted">${tr('Курс, установленный в рамках проекта.','Project exchange rate.')}</p></div><div class="card"><span class="badge">RHD</span><h2>${tr('Дизайн в разработке','Design in development')}</h2><p class="muted">${tr('1 октября 2026 года начата разработка нового дизайна государственной валюты.','Development of the new state currency design started on 1 October 2026.')}</p></div></div>`}
function newsPage(){return `<div class="page-title"><div class="eyebrow">${tr('Хроника','Chronicle')}</div><h1>${tr('Новости','News')}</h1></div><div class="news">${news.map(n=>`<article class="card newsitem"><div class="muted">${n[0]}</div><h2><a href="#/news/${n[3]}">${n[1]}</a></h2><p>${n[2]}</p></article>`).join('')}</div>`}
function newsDetail(id){const n=news.find(x=>x[3]===id)||news[3];return `<div class="page-title"><div class="eyebrow">${n[0]}</div><h1>${n[1]}</h1></div><article class="card"><p>${n[2]}</p><p>${tr('Это расширенное описание новости в рамках хроники вымышленной Республики. Здесь можно хранить дополнительные сведения, документы и изображения, относящиеся к записи.','This is an expanded article in the fictional Republic’s chronicle. Additional notes, documents and images can be attached here.')}</p><button class="btn" onclick="go('/news')">${tr('Назад к новостям','Back to news')}</button></article>`}
function about(){return `<div class="page-title"><div class="eyebrow">${tr('Информация','Information')}</div><h1>${tr('О проекте','About the project')}</h1></div><div class="card"><p>${tr('Израильская Ростовская Народная Республика — вымышленный ролевой и юмористический проект. Это не настоящее государство и не государственный сервис. Имена, должности, документы, события и нормы используются внутри лора проекта. Упоминание реальных имён или изображений не означает реального участия соответствующих людей.','Israel Rostov People’s Republic is a fictional roleplay and humour project. It is not a real state or government service. Names, offices, documents, events and rules are used only within the project lore. Mentioning real names or images does not imply participation by those people.')}</p></div>`}
function render(){const p=location.hash.replace(/^#/,'')||'/';if(APP.citizen&&p==='/cabinet')return renderCabinet(APP.citizen);let c=p==='/'?home():p==='/citizens'?citizensPage():p==='/constitution'?constitution():p==='/cabinet'?cabinet():p==='/education'?service('education'):p==='/health'?service('health'):p==='/currency'?currency():p==='/news'?newsPage():p==='/about'?about():p.startsWith('/news/')?newsDetail(p.split('/')[2]):home();layout(c);if(p==='/constitution')loadConstitution()}
function toast(s){const x=document.getElementById('toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
window.addEventListener('hashchange',render);window.go=go;window.toggleDark=toggleDark;window.toggleLang=toggleLang;window.profile=profile;window.kOn=kOn;window.closeModal=closeModal;window.login=login;window.submitService=submitService;window.renderCabinet=renderCabinet;window.onload=render;
